name: Clinic-Cal Ingest - Epic Availability

on:
  # Run daily at 15:00 UTC which is 07:00 PST or 08:00 PDT
  # PST is UTC-8 (Nov to Mar) and PDT is UTC-7 (Mar to Nov)
  # No timezone support for GH Actions yet. See https://github.com/orgs/community/discussions/13454
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  run-clinic-cal-ingest:
    runs-on: self-hosted
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          repository: jonjlee/clinic-cal
          token: ${{ secrets.CLINIC_CAL_RO_PAT }}
          path: clinic-cal

      - name: Run ingest
        run: |
          pushd clinic-cal

          # Load env vars from project, then run script
          set -a; source epic/.env
          npm install && node epic/ingest-provider-schedule.cjs -f "${CLINIC_CAL_EPIC_SOURCE_FILE}" -out "${CLINIC_CAL_EPIC_URL}"
