name: Ingest

on:
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  run-sources-epic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Execute sources-epic
        run: node pipeline/trigger_workflows.js sources-epic

  await-sources-epic:
    runs-on: ubuntu-latest
    needs: run-sources-epic
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Poll for sources-epic completion
        run: node pipeline/poll_workflows.js sources-epic
