name: "* Ingest Source Data"

on:
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  run-ingest-sources:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ingest source data
        run: |
          env
          pushd ingest
          pipenv install && pipenv run python main.py
        env:
          PIPENV_CUSTOM_VENV_NAME: "prh-warehouse"
          PRW_ENV: ${{ env.PRW_ENV || 'prod' }}
          PRW_HOME: ${{ env.PRW_HOME || '.' }}
