name: Sources Epic

on:
  workflow_dispatch:
    inputs:
      sql_script_to_run:
        description: 'SQL Script to Run (optional)'
        required: false
        type: string

jobs:
  run-sources-epic:
    runs-on: self-hosted
    steps:
      - name: Checkout prw-exporter
        uses: actions/checkout@v4
        with:
          repository: pullmanregional/prw-exporter
          token: ${{ secrets.DEPLOY_PAT }}
          path: prw-exporter
          submodules: true

      - name: Run script
        run: |
          # Load env variables from .env.prod
          if [ -f "prw-exporter/sources/epic/prefect/.env.prod" ]; then
            echo "Loading environment variables from .env.prod"
            set -a; source prw-exporter/sources/epic/prefect/.env.prod; set +a
            env
          else
            echo "Warning: .env.prod file not found"
          fi

          # Run script
          cd prw-exporter/sources/epic
          pipenv install --deploy
          if [ -n "${{ inputs.sql_script_to_run }}" ]; then
            pipenv run python run_sql_scripts.py --caboodle "${{ secrets.CABOODLE_CONN }}" --clarity "${{ secrets.CLARITY_CONN }}" --out "$PRH_SOURCES_EPIC_OUTPUT_PATH" --script "${{ inputs.sql_script_to_run }}"
          else
            pipenv run python run_sql_scripts.py --caboodle "${{ secrets.CABOODLE_CONN }}" --clarity "${{ secrets.CLARITY_CONN }}" --out "$PRH_SOURCES_EPIC_OUTPUT_PATH"
          fi
        env:
          PIPENV_CUSTOM_VENV_NAME: sources-epic
