name: Export Source - Epic

on:
  workflow_dispatch:
    inputs:
      sql_script_to_run:
        description: 'SQL Script to Run (optional)'
        required: false
        type: string

jobs:
  run-sources-epic:
    runs-on: self-hosted
    steps:
      - name: Checkout prw-exporter
        uses: actions/checkout@v4
        with:
          repository: pullmanregional/prw-exporter
          token: ${{ secrets.DEPLOY_PAT }}
          path: prw-exporter
          submodules: true

      - name: Run script
        run: |
          pushd prw-exporter/sources/epic

          # Load env vars based on environment designated in PRW_ENV
          set -a; source prefect/.env.$PRW_ENV

          # Run script
          [ -n "${{ inputs.sql_script_to_run }}" ] && SCRIPT_FLAG="--script ${{ inputs.sql_script_to_run }}"
          uv run python run_sql_scripts.py --caboodle "$CABOODLE_CONN" --clarity "$CLARITY_CONN" --out "$PRH_SOURCES_EPIC_OUTPUT_PATH" $SCRIPT_FLAG
        env:
          PIPENV_CUSTOM_VENV_NAME: "prw-exporter"
          PRW_ENV: ${{ env.PRW_ENV || 'prod' }}
          CABOODLE_CONN: ${{ secrets.CABOODLE_CONN }}
          CLARITY_CONN: ${{ secrets.CLARITY_CONN }}
